:author: Arnar Van Rysselberghe, Toon Van de Voorde, Nathalie Van Bellegem, Maxime Vierstraete, Mathias Van Rumst
:revnumber: v1.1
:title: SUC SUC_AO - aanwezigheden opnemen

== BUC_AO - aanwezigheden opnemen

De docent registreert de aanwezigheden van alle studenten

=== Actors

**Docent**, Student, Secretariaatsmedewerker

=== Preconditie
De docent heeft een namenlijst van de klasgroep van het secretariaat


=== Basispad

. De [.underline]#docent# wil de aanwezigheden van de [.underline]#studenten# opnemen
. De [.underline]#docent# neemt de klassenlijst.
. De [.underline]#docent# roept de naam van de [.underline]#student# .
. De [.underline]#student# geeft zijn studentenkaart aan de [.underline]#docent# .
. De [.underline]#docent# controleert of de naam van de [.underline]#student# correct is.
. De [.underline]#docent# noteert dat de [.underline]#student# aanwezig is.
. De [.underline]#docent# herhaalt stappen 3, tot en met 6 tot alle namen zijn afgelopen.
. De [.underline]#docent# geeft de klassenlijst aan de [.underline]#secretariaatsmedewerker#
. De use case eindigt.

**Postconditie**
De namenlijst van de klasgroep is ingevuld.


=== Alternatief A: Student is afwezig
. De [.underline]#student# komt niet naar voren als deze geroepen wordt.
. De use case eindigt.

*Postconditie*

-

=== Alternatief B: De student heeft zijn studentenkaart niet bij
. De [.underline]#docent# kan niet bevestigen dat de aanwezige student ingeschreven is.
. De use case eindigt.


